version: "3.8"

services:
  minio:
    image: minio/minio:latest
    volumes:
      - data:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address :9001 /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

    restart: unless-stopped

  server:
    build:
      context: .
      target: development # specify target stage in Dockerfile
      dockerfile: ./Dockerfile
    container_name: file-upload-server
    restart: unless-stopped
    environment:
      # passing env to container
      - SERVER_PORT=${SERVER_PORT}
    ports:
      # map host port to container port
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/usr/src/server/src # map directory to container for hot reloading
      - /usr/src/node_modules # map node_modules directory

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      # map configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

volumes:
  data:
